### ISSUE TITLE
missing references to antescofo_New

### ISSUE THREAD

**Issue by johndpope** [k4rm/AscoGraph#1]
In the app - there's a reference to the 

set (ANTESCOFO_LIB_PATH ${OPENFRAMEWORKS_ROOT}/../antescofo_New )
set (ANTESCOFO_PARSER_INCL_PATH ${ANTESCOFO_LIB_PATH}/includes ${ANTESCOFO_LIB_PATH}/parser)

The library isn't included - so I can't get the app to build. 
Any chance you can commit or email me the libantescofo_parser.a and libSGUIDOEngine and associated header files? I don't think I need the antescofo library / project if that's your concern. 

I may end up pulling the entire project apart as I'm interested in the models around music not so much the ui. Do you know if you have successfully represented the rests in your code? 
I couldn't see any in screen shots. I know this doesn't exist in musicxml / midi - but I need them for my algorithm.

Thanks in advance

P.S. In compile sources - it's saying main.mm is missing. 

If you can have someone else try to check out the project and compile on a different machine - it may save me going back and forth to you. 

![unnamed](https://cloud.githubusercontent.com/assets/289994/9050392/9233ee76-3a90-11e5-91a6-3300a8d54a87.png)

**Comment by johndpope** [comment]
@k4rm - it's a shame this library was never included without it - the codebase couldn't compile.
Thanks for your efforts in any case.

**Comment by arshiacont** [comment]
@johndpope : I'm sorry no one has come back to you on this. As we speak, we are in process of cleaning out the project and negociating so that the required library become visible for everyone. This will happen soon.

However, and meanwhile, most of the OFx libraries used in the project have become deprecated and the App does _not_ compile as is on newer Macs. This requires a profound revisit of the fundamentals of the app and a lot of resources.

Therefore the future of AscoGraph as of today is somehow uncertain.

**Comment by johndpope** [comment]
with time machine - and backups - it could be possible to press run / compile on ancient xcode to build to an older device.  but without library - it's a lost cause.
